# https://taskfile.dev
version: "3"

vars:
  EXTENSION_NAME: single-line-multi-line
  PUBLISHER: TobiasHochguertel
  DEMO_DIR: demos
  DEMO_01_DIR: "{{.DEMO_DIR}}/01-svg-frames"
  DEMO_02_DIR: "{{.DEMO_DIR}}/02-vscode-test-electron"
  DEMO_03_DIR: "{{.DEMO_DIR}}/03-puppeteer"
  DEMO_04_DIR: "{{.DEMO_DIR}}/04-vscode-demo-recorder"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  # ── Development ──────────────────────────────────────────────

  install:
    desc: Install dependencies
    cmds:
      - npm install
    sources:
      - package.json

  compile:
    desc: Compile the extension with esbuild
    cmds:
      - npm run compile

  watch:
    desc: Watch for changes and recompile
    cmds:
      - npm run watch

  lint:
    desc: Run ESLint on source files
    cmds:
      - npm run lint

  # ── Testing ──────────────────────────────────────────────────

  test:
    desc: Run all tests
    cmds:
      - npm test

  test:unit:
    desc: Run unit tests
    cmds:
      - npm run test:unit

  test:unit:watch:
    desc: Run unit tests in watch mode
    cmds:
      - npm run test:unit:watch

  # ── Packaging ────────────────────────────────────────────────

  package:
    desc: Package the extension into a .vsix file
    deps: [compile]
    cmds:
      - npx @vscode/vsce package
    generates:
      - "*.vsix"

  # ── Publishing ───────────────────────────────────────────────
  #
  # Token setup (sourced from ~/dotfiles/shell_zsh/tokens.zsh):
  #   VS Code Marketplace:  export VSCE_PAT="$AZURE_DEV_OPS_TOKEN"
  #   Open VSX Registry:    export OVSX_PAT="..."  (already exported)
  #

  publish:vscode:
    desc: Publish to VS Code Marketplace
    deps: [package]
    cmds:
      - npx @vscode/vsce publish
    preconditions:
      - sh: test -n "$VSCE_PAT"
        msg: 'VSCE_PAT environment variable must be set (export VSCE_PAT="$AZURE_DEV_OPS_TOKEN")'

  publish:openvsx:
    desc: Publish to Open VSX Registry
    deps: [package]
    cmds:
      - npx ovsx publish *.vsix -p $OVSX_PAT
    preconditions:
      - sh: test -n "$OVSX_PAT"
        msg: "OVSX_PAT environment variable must be set"

  publish:all:
    desc: Publish to both VS Code Marketplace and Open VSX
    deps: [publish:vscode, publish:openvsx]

  # ── Version bumping ─────────────────────────────────────────

  version:bump:
    desc: "Bump version (usage: task version:bump -- <major|minor|patch>)"
    cmds:
      - npm version {{.CLI_ARGS}} --no-git-tag-version
      - git add package.json package-lock.json
      - 'git commit -m "chore: bump version to $(node -p \"require(''./package.json'').version\")"'

  version:patch:
    desc: Bump patch version
    cmds:
      - task version:bump -- patch

  version:minor:
    desc: Bump minor version
    cmds:
      - task version:bump -- minor

  version:major:
    desc: Bump major version
    cmds:
      - task version:bump -- major

  # ── Release workflow ─────────────────────────────────────────

  release:
    desc: "Create a new release (usage: task release -- <major|minor|patch>)"
    cmds:
      - task: lint
      - task: test
      - task: version:bump
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"
      - git tag v$(node -p "require('./package.json').version")
      - git push origin main --tags
      - task: publish:all

  # ── Maintenance ──────────────────────────────────────────────

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf out *.vsix

  sync-upstream:
    desc: Fetch and merge changes from the upstream (original) repository
    cmds:
      - git fetch upstream
      - git merge upstream/main --no-edit
    status:
      - git remote get-url upstream

  outdated:
    desc: Check for outdated dependencies
    cmds:
      - npm outdated || true

  security:audit:
    desc: Run security audit
    cmds:
      - npm audit

  ci:
    desc: Run CI checks (lint, compile, test)
    cmds:
      - task: lint
      - task: compile
      - task: test

  debug:
    desc: Launch extension in debug mode
    cmds:
      - code --extensionDevelopmentPath=$(pwd)

  # ── Demo GIF Recording ─────────────────────────────────────
  #
  # Multiple solutions available — see demos/README.md
  #

  demo:install:
    desc: "Install dependencies for all demo solutions"
    dir: "{{.DEMO_DIR}}"
    preconditions:
      # Check if `bun` is installed
      - bun --version
    cmds:
      - bun install

  vscode-test:cleanup:
    desc: "Clean VS Code Test artifacts"
    status:
      - test -d .vscode-test
    cmds:
      - rm -rf .vscode-test || true

  demo:cleanup:
    desc: "Clean output directories, compiled files, and temporary files of a given solution"
    vars:
      SOLUTION_DIR: '{{.SOLUTION_DIR| default ""}}'
    cmds:
      - echo "Cleaning {{.SOLUTION_DIR}}"
      - task: vscode-test:cleanup
      - rm -rf {{.SOLUTION_DIR}}/out || true
      - rm -rf {{.SOLUTION_DIR}}/output || true
      - rm -rf {{.SOLUTION_DIR}}/scripts/find-window-id || true
    preconditions:
      - sh: test -d {{.SOLUTION_DIR}}
        msg: 'Solution directory "{{.SOLUTION_DIR}}" does not exist'

  demo:clean:
    desc: Remove all demo output artifacts
    cmds:
      - task: demo:01:clean
      - task: demo:02:clean
      - task: demo:03:clean
      - task: demo:04:clean

  # ── Solution 01: SVG frames ────────────────────────────────

  demo:01:clean:
    desc: "Clean output directories, compiled files, and temporary files of solution 01"
    cmds:
      - task: demo:cleanup
        vars:
          SOLUTION_DIR: "{{.DEMO_01_DIR}}"

  demo:01:compile:
    desc: "Solution 01: Compile scenario runner"
    deps: [compile, demo:install]
    cmds:
      - npx tsc -p {{.DEMO_01_DIR}}/tsconfig.json

  demo:01:frames:
    desc: "Solution 01: Generate SVG frames"
    deps: [demo:01:compile]
    cmds:
      - bun {{.DEMO_01_DIR}}/src/generate-frames.ts {{.CLI_ARGS | default "all"}}

  demo:01:assemble:
    desc: "Solution 01: Assemble SVG frames into GIFs"
    deps: [demo:01:compile]
    cmds:
      - ./{{.DEMO_01_DIR}}/scripts/assemble-gif.sh {{.CLI_ARGS | default "all"}}

  demo:01:generate:
    desc: "Solution 01: Generate frames + assemble GIFs"
    deps: [demo:01:compile]
    cmds:
      - task: demo:01:frames
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"
      - task: demo:01:assemble
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  # ── Solution 02: vscode-test-electron (original) ──────────────

  demo:02:debug:
    desc: "Solution 02: Launch VS Code and record screenshots (debug mode)"
    # deps: [demo:02:compile]
    cmds:
      # - bun {{.DEMO_02_DIR}}/src/launch.ts {{.CLI_ARGS | default "all"}}
      - |
        "/Users/tobiashochgurtel/work-dev/temp-projects/compare-vscode-extension_inline-fold/vscode-ext-single-multi-line/.vscode-test/vscode-darwin-arm64-1.109.2/Visual Studio Code.app/Contents/Resources/app/bin/code" --verbose --log debug --extensions-dir=/Users/tobiashochgurtel/work-dev/temp-projects/compare-vscode-extension_inline-fold/vscode-ext-single-multi-line/.vscode-test/extensions --user-data-dir=/Users/tobiashochgurtel/work-dev/temp-projects/compare-vscode-extension_inline-fold/vscode-ext-single-multi-line/.vscode-test/user-data /Users/tobiashochgurtel/work-dev/temp-projects/compare-vscode-extension_inline-fold/vscode-ext-single-multi-line/demos/fixtures --extensionDevelopmentPath=/Users/tobiashochgurtel/work-dev/temp-projects/compare-vscode-extension_inline-fold/vscode-ext-single-multi-line --extensionTestsPath=/Users/tobiashochgurtel/work-dev/temp-projects/compare-vscode-extension_inline-fold/vscode-ext-single-multi-line/demos/02-vscode-test-electron/out/src/run-scenarios --wait --disable-gpu --skip-welcome --skip-release-notes --disable-workspace-trust

  demo:02:clean:
    desc: "Clean output directories, compiled files, and temporary files of solution 02"
    cmds:
      - task: demo:cleanup
        vars:
          SOLUTION_DIR: "{{.DEMO_02_DIR}}"

  demo:02:compile:
    desc: "Solution 02: Compile scenario runner + Swift helper for VS Code Electron"
    deps: [compile, demo:install]
    cmds:
      - npx tsc -p {{.DEMO_02_DIR}}/tsconfig.json
      - >-
        test -f {{.DEMO_02_DIR}}/scripts/find-window-id && test {{.DEMO_02_DIR}}/scripts/find-window-id -nt {{.DEMO_02_DIR}}/scripts/find-window-id.swift || swiftc -O {{.DEMO_02_DIR}}/scripts/find-window-id.swift -o {{.DEMO_02_DIR}}/scripts/find-window-id
      - chmod +x {{.DEMO_02_DIR}}/scripts/find-window-id

  demo:02:record:
    desc: "Solution 02: Launch VS Code and record screenshots"
    deps: [demo:02:compile]
    cmds:
      - bun {{.DEMO_02_DIR}}/src/launch.ts {{.CLI_ARGS | default "all"}}

  demo:02:assemble:
    desc: "Solution 02: Assemble screenshots into GIFs"
    cmds:
      - ./{{.DEMO_02_DIR}}/scripts/assemble-gif.sh {{.CLI_ARGS | default "all"}}

  demo:02:update-goldens:
    desc: "Solution 02: Run scenarios and write/update golden files"
    deps: [demo:02:compile]
    env:
      UPDATE_GOLDENS: "1"
    cmds:
      - bun {{.DEMO_02_DIR}}/src/launch.ts {{.CLI_ARGS | default "all"}}

  demo:02:generate:
    desc: "Solution 02: Compile + record + assemble GIFs (verifies goldens)"
    deps: [demo:02:compile]
    cmds:
      - task: demo:02:record
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"
      - task: demo:02:assemble
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  # ── Solution 04: vscode-demo-recorder (enhanced CLI) ──────────

  demo:04:clean:
    desc: "Clean output directories, compiled files, and temporary files of solution 04"
    cmds:
      - task: demo:cleanup
        vars:
          SOLUTION_DIR: "{{.DEMO_04_DIR}}"

  demo:04:compile:
    desc: "Solution 04: Compile scenario runner + Swift helper"
    deps: [compile, demo:install]
    cmds:
      - npx tsc -p {{.DEMO_04_DIR}}/tsconfig.json
      - >-
        test -f {{.DEMO_04_DIR}}/scripts/find-window-id && test {{.DEMO_04_DIR}}/scripts/find-window-id -nt {{.DEMO_04_DIR}}/scripts/find-window-id.swift || swiftc -O {{.DEMO_04_DIR}}/scripts/find-window-id.swift -o {{.DEMO_04_DIR}}/scripts/find-window-id
      - chmod +x {{.DEMO_04_DIR}}/scripts/find-window-id

  demo:04:schema:
    desc: "Solution 04: Generate JSON Schema from Zod definitions"
    deps: [demo:04:compile]
    cmds:
      - bun {{.DEMO_04_DIR}}/scripts/generate-schema.ts

  demo:04:record:
    desc: "Solution 04: Launch VS Code and record screenshots (config-driven)"
    deps: [demo:04:compile]
    cmds:
      - bun {{.DEMO_04_DIR}}/src/launch.ts {{.CLI_ARGS | default "all"}}

  demo:04:assemble:
    desc: "Solution 04: Assemble screenshots into GIFs (config-driven)"
    deps: [demo:04:compile]
    cmds:
      - bun {{.DEMO_04_DIR}}/src/cli.ts assemble {{.CLI_ARGS | default "all"}}

  demo:04:update-goldens:
    desc: "Solution 04: Run scenarios and write/update golden files"
    deps: [demo:04:compile]
    cmds:
      - bun {{.DEMO_04_DIR}}/src/launch.ts {{.CLI_ARGS | default "all"}} --update-goldens

  demo:04:generate:
    desc: "Solution 04: Clean + compile + record + assemble GIFs"
    deps: [demo:04:compile]
    cmds:
      - task: demo:04:clean
      - task: demo:04:record
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"
      - task: demo:04:assemble
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  # ── Solution 03: Puppeteer (original) ────────────────────────

  demo:03:clean:
    desc: "Clean output directories, compiled files, and temporary files of solution 03"
    cmds:
      - task: demo:cleanup
        vars:
          SOLUTION_DIR: "{{.DEMO_03_DIR}}"

  demo:03:compile:
    desc: "Solution 03: Compile scenario runner"
    deps: [compile, demo:install]
    cmds:
      - npx tsc -p {{.DEMO_03_DIR}}/tsconfig.json

  demo:03:capture:
    desc: "Solution 03: Capture screenshots via Puppeteer"
    deps: [demo:03:compile]
    cmds:
      - bun {{.DEMO_03_DIR}}/src/capture.ts {{.CLI_ARGS | default "all"}}

  demo:03:assemble:
    desc: "Solution 03: Assemble Puppeteer screenshots into GIFs"
    deps: [demo:03:compile]
    cmds:
      - ./{{.DEMO_03_DIR}}/scripts/assemble-gif.sh {{.CLI_ARGS | default "all"}}

  demo:03:generate:
    desc: "Solution 03: Capture + assemble GIFs (Puppeteer)"
    deps: [demo:03:compile]
    cmds:
      - task: demo:03:capture
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"
      - task: demo:03:assemble
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"
